version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./app/sql/init:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=insurance
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/insurance
      - EMAIL_HOST=smtp.yandex.ru
      - EMAIL_PORT=587
      - EMAIL_USERNAME= ilosipenko@edu.hse.ru
      - EMAIL_PASSWORD=mirjmgxpzrhyeapp
      - SECRET_KEY=549nc4eg=t92&)b)_ebhlpk)b8i)-ju6(8uqt*(g!8gi1fy8!

volumes:
  postgres_data: